### ISSUE TITLE
disable URL-based sessions

### ISSUE THREAD

**Issue by r3j** [stefanesser/suhosin#109]
any way? 수호신

**Comment by bef** [comment]
How about setting `session.use_trans_sid` to false?

**Comment by r3j** [comment]
script still use.

**Comment by bef** [comment]
`session.use_trans_sid` may have been set in `.htaccess` within your script's directory or any parent directory. Please recheck, e.g. via `phpinfo()`.

**Comment by r3j** [comment]
nginx, ty i try @ini_set('session.use_trans_sid', 0);

**Comment by bef** [comment]
your should also have a look at `session.use_cookies` and `session.use_only_cookies`:
http://php.net/manual/en/session.configuration.php

As these questions relate to PHP and/or nginx configuration rather than suhosin, I would like to direct this discussion to a more suitable board, e.g. http://stackoverflow.com/questions/1745984/php-session-use-trans-sid
